receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
  hostmetrics:
    scrapers:
      load:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      paging:
      process:

processors:
  batch:
    timeout: 10s

extensions:
  health_check: {}

exporters:
  jaeger:
    endpoint: "127.0.0.1:14250"
    insecure: true
  datadog:
    api:
      key: "b7b38d320339064689dc55f5115d2a8e"
  logging:
  
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger,datadog]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]